
let products = [

  {
    id: 1,
    number: 1001,
    img: 'img/crank-1.png',
    title: 'Crank 60F-10',
    type: 'Крэнк',
    length: 60,
    weight: 10,
    availability: 'Нет',
    price: 1000,
  },
  {
    id: 2,
    number: 1002,
    img: 'img/crank-2.png',
    title: 'Crank 80F-15',
    type: 'Крэнк',
    length: 80,
    weight: 15,
    availability: 'Нет',
    price: 1100,
  },
  {
    id: 3,
    number: 1003,
    img: 'img/crank-3.png',
    title: 'Crank 100F-20',
    type: 'Крэнк',
    length: 100,
    weight: 20,
    availability: 'Да',
    price: 1200,
  },
  {
    id: 4,
    number: 2001,
    img: 'img/jerkbait-1.png',
    title: 'Jerkbait 90F-30',
    type: 'Джеркбейт',
    length: 90,
    weight: 30,
    availability: 'Да',
    price: 1350,
  },
  {
    id: 5,
    number: 2002,
    img: 'img/jerkbait-2.png',
    title: 'Jerkbait 100S-40',
    type: 'Джеркбейт',
    length: 100,
    weight: 40,
    availability: 'Нет',
    price: 1500,
  },
  {
    id: 6,
    number: 2003,
    img: 'img/jerkbait-3.png',
    title: 'Jerkbait 150F-50',
    type: 'Джеркбейт',
    length: 150,
    weight: 50,
    availability: 'Да',
    price: 1800,
  },

  {
    id: 7,
    number: 3001,
    img: 'img/glisser-1.png',
    title: 'Glisser 30F-5',
    type: 'Глиссер',
    length: 30,
    weight: 5,
    availability: 'Да',
    price: 500,
  },
  {
    id: 8,
    number: 3002,
    img: 'img/glisser-2.png',
    title: 'Glisser 40F-10',
    type: 'Глиссер',
    length: 40,
    weight: 10,
    availability: 'Нет',
    price: 600,
  },
  {
    id: 9,
    number: 3003,
    img: 'img/glisser-3.png',
    title: 'Glisser 50F-15',
    type: 'Глиссер',
    length: 50,
    weight: 15,
    availability: 'Да',
    price: 700,
  },
  {
    id: 10,
    number: 4001,
    img: 'img/minnow-1.png',
    title: 'Minnow 70F-15',
    type: 'Минноу',
    length: 70,
    weight: 15,
    availability: 'Да',
    price: 800,
  },
  {
    id: 11,
    number: 4002,
    img: 'img/minnow-2.png',
    title: 'Minnow 70S-25',
    type: 'Минноу',
    length: 70,
    weight: 25,
    availability: 'Нет',
    price: 900,
  },
  {
    id: 12,
    number: 4003,
    img: 'img/minnow-3.png',
    title: 'Minnow 80F-20',
    type: 'Минноу',
    length: 80,
    weight: 20,
    availability: 'Да',
    price: 850,
  },
  {
    id: 13,
    number: 5001,
    img: 'img/popper-1.png',
    title: 'Popper 40F-5',
    type: 'Поппер',
    length: 40,
    weight: 5,
    availability: 'Да',
    price: 650,
  },
  {
    id: 14,
    number: 5002,
    img: 'img/popper-2.png',
    title: 'Popper 50F-10',
    type: 'Поппер',
    length: 50,
    weight: 10,
    availability: 'Нет',
    price: 750,
  },
  {
    id: 15,
    number: 5003,
    img: 'img/popper-3.png',
    title: 'Popper 60F-15',
    type: 'Поппер',
    length: 60,
    weight: 15,
    availability: 'Нет',
    price: 800,
  },
  {
    id: 16,
    number: 6001,
    img: 'img/rattlin-1.png',
    title: 'Rattlin 70S-20',
    type: 'Раттлин',
    length: 70,
    weight: 20,
    availability: 'Нет',
    price: 1000,
  },
  {
    id: 17,
    number: 6002,
    img: 'img/rattlin-2.png',
    title: 'Rattlin 90S-30',
    type: 'Раттлин',
    length: 90,
    weight: 30,
    availability: 'Нет',
    price: 1150,
  },
  {
    id: 18,
    number: 6003,
    img: 'img/rattlin-3.png',
    title: 'Rattlin 110S-40',
    type: 'Раттлин',
    length: 110,
    weight: 40,
    availability: 'Да',
    price: 1200,
  },
  {
    id: 19,
    number: 7001,
    img: 'img/shad-1.png',
    title: 'Shad 90F-20',
    type: 'Шэд',
    length: 90,
    weight: 20,
    availability: 'Да',
    price: 900,
  },
  {
    id: 20,
    number: 7002,
    img: 'img/shad-2.png',
    title: 'Shad 100F-25',
    type: 'Шэд',
    length: 100,
    weight: 25,
    availability: 'Нет',
    price: 950,
  },
  {
    id: 21,
    number: 7003,
    img: 'img/shad-3.png',
    title: 'Shad 120F-30',
    type: 'Шэд',
    length: 120,
    weight: 30,
    availability: 'Да',
    price: 1100,
  },
  {
    id: 22,
    number: 8001,
    img: 'img/swimbait-1.png',
    title: 'Swimbait 70S-10',
    type: 'Свимбейт',
    length: 70,
    weight: 10,
    availability: 'Да',
    price: 1200,
  },
  {
    id: 23,
    number: 8002,
    img: 'img/swimbait-2.png',
    title: 'Swimbait 80S-15',
    type: 'Свимбейт',
    length: 80,
    weight: 15,
    availability: 'Да',
    price: 1400,
  },
  {
    id: 24,
    number: 8003,
    img: 'img/swimbait-3.png',
    title: 'Swimbait 90S-20',
    type: 'Свимбейт',
    length: 90,
    weight: 20,
    availability: 'Нет',
    price: 1600,
  },
  {
    id: 25,
    number: 9001,
    img: 'img/walker-1.png',
    title: 'Walker 60F-10',
    type: 'Волкер',
    length: 60,
    weight: 10,
    availability: 'Нет',
    price: 700,
  },
  {
    id: 26,
    number: 9002,
    img: 'img/walker-2.png',
    title: 'Walker 75F-15',
    type: 'Волкер',
    length: 75,
    weight: 15,
    availability: 'Да',
    price: 850,
  },
  {
    id: 27,
    number: 9003,
    img: 'img/walker-3.png',
    title: 'Walker 90F-20',
    type: 'Волкер',
    length: 90,
    weight: 20,
    availability: 'Да',
    price: 1000,
  },  

]

export default products; // export products
